name: Build and deploy the Auth service to production

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ${{ github.repository }}:latest
          platforms: linux/amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      ## Send result to discord
      -
        name: Send discord failure message
        if: ${{ failure() }}
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: "https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
          colour: "#FF0000"
          title: ":japanese_goblin: Failed to build image for ${{ github.repository }}"
          message: "${{ github.event.commits[0].message }}"
          title_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"
          avatar_url: "https://github.com/todanni/auth/blob/main/images/account-lock-outline.png?raw=true"

      -
        name: Send discord success message
        if: ${{ success() }}
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: "https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
          colour: "#48f442"
          title: ":tools: Successfully built image for ${{ github.repository }}"
          message: "${{ github.event.commits[0].message }}"
          title_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"
          avatar_url: "https://github.com/todanni/auth/blob/main/images/account-lock-outline.png?raw=true"

      ## Send result to discord
  run:
    runs-on: self-hosted
    needs: [build]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        ## Run
      -
        name: Run
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: danni-popova
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ## Traefik labels
          HOST_LABEL: traefik.http.routers.${{ github.event.repository.name }}.rule=Host(`api.todanni.com`)
          TLS_CERT_LABEL: traefik.http.routers.${{ github.event.repository.name }}.tls.certresolver=letsencrypt
          TLS_LABEL: traefik.http.routers.${{ github.event.repository.name }}.tls=true
          ENABLE_LABEL: traefik.enable=true
          
          CORS_METHOD: traefik.http.middlewares.${{ github.event.repository.name }}-cors.headers.accessControlAllowMethods=*
          CORS_ALLOW: traefik.http.middlewares.${{ github.event.repository.name }}-cors.headers.accessControlAllowOriginList=https://todanni.com
          CORS_MAX_AGE: traefik.http.middlewares.${{ github.event.repository.name }}-cors.headers.accessControlMaxAge=100
          CORS_VARY: traefik.http.middlewares.${{ github.event.repository.name }}-cors.headers.addVaryHeader=true
          CORS_CRED: traefik.http.middlewares.${{ github.event.repository.name }}-cors.headers.accessControlAllowCredentials=true
          CORS_HEADERS: traefik.http.middlewares.${{ github.event.repository.name }}-cors.headers.accessControlAllowHeaders=authorization
          CORS_MIDDLEWARE: traefik.http.routers.${{ github.event.repository.name }}.middlewares=${{ github.event.repository.name }}-cors@docker

        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.ADMIN_SSH_KEY }}
          envs:  HOST_LABEL,TLS_CERT_LABEL,TLS_LABEL,ENABLE_LABEL,CORS_METHOD,CORS_ALLOW,CORS_MAX_AGE,CORS_VARY,CORS_CRED,CORS_HEADERS,CORS_MIDDLEWARE
          script: |
            VAULT_ADDR='https://vault.todanni.com' VAULT_API_SERVICE_TOKEN=${{ secrets.VAULT_TOKEN }} vault kv get -format yaml -field data  ci/${{ github.event.repository.name }} > .env
            sed -i 's/: /=/g' .env
            sed -i 's/"//g' .env
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull ${{ github.repository }}:latest
            docker rm -f ${{ github.event.repository.name }} 
            docker run -d --name ${{ github.event.repository.name }} --network ${{ secrets.NETWORK }} -l "$HOST_LABEL" -l "$TLS_LABEL" -l "$TLS_CERT_LABEL" -l "$ENABLE_LABEL" -l "$CORS_ALLOW" -l "$CORS_METHOD" -l "$CORS_MAX_AGE" -l "$CORS_VARY" -l "$CORS_CRED" -l "$CORS_HEADERS" -l "$CORS_MIDDLEWARE" --env-file .env  ${{ github.repository }}
      -
        name: Send discord failure message
        if: ${{ failure() }}
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: "https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
          colour: "#FF0000"
          title: ":boom: Failed to deploy latest image for ${{ github.repository }}"
          message: "${{ github.event.commits[0].message }}"
          title_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"
          avatar_url: "https://github.com/todanni/auth/blob/main/images/account-lock-outline.png?raw=true"

      -
        name: Send discord success message
        if: ${{ success() }}
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: "https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_ID }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
          colour: "#48f442"
          title: ":rocket: Successfully deployed latest image to production for ${{ github.repository }}"
          message: "${{ github.event.commits[0].message }}"
          title_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"
          avatar_url: "https://github.com/todanni/auth/blob/main/images/account-lock-outline.png?raw=true"
